# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
#    - name: Install dependencies
#      run: |
#        python -m pip install --upgrade pip
#        pip install imohash
#    - name: Run imohash
#      run: |
#        python imohash_test.py
    - name: Run hasher
      run: |
        python gethash.py
    - name: Commit hash
      run: |
        git config --global user.name 'Izzak'
        git config --global user.email 'tomas-dockal@seznam.cz'
#        git add --force hash.txt
        git add --force filelist.xml
        git commit -m "Autohashing" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
